version: "3.7"
services:
  app:
    build: .
    env_file:
      - model.env
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
